name: voice_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  # アイコンなど
  cupertino_icons: ^1.0.6

  # データベース (Isar)
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2
  
  # 録音・再生
  record: ^4.4.4
  just_audio: ^0.9.32
  
  # AI (Gemini)
  google_generative_ai: ^0.4.0
  
  # 共有
  share_plus: ^10.0.0
  
  # ユーティリティ
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 開発用ツール
  flutter_lints: ^3.0.0
  
  # コード生成ツール (Isar用)
  build_runner: ^2.4.8
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true